version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/backend_node_express/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7.4.0-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  fastapi:
    build:
      context: .
      dockerfile: docker/backend_fastapi/Dockerfile
    container_name: fastapi_container
    image: fastapi/app
    ports:
      - '8001:8001'
    volumes:
      - './fastapi:/usr/src/fastapi'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
